// import mongoose from "mongoose";

// const SurveySchema = new mongoose.Schema({
//   fullname:String,
//   role:  String,
//   CoachesName:String,
//   ManagersName:String,
//   EmploymentDate:String,
//   CurrentAUM:String,
//   NumberofClients :String,
//   TopStrengths :String,
//   Strength1:String,
//   Anymismanagement1:String,
//   Strength2:String,
//   Anymismanagement2:String,
//   Goal1:String,
//   Goal2:String,
//   Goal3:String,
//   Goal4:String,
//   Opportunity1:String,
//   Opportunity2:String,
//   Opportunity3:String,
//   Opportunity4:String,
//   Spiritual:String,
//   Intellectual:String,
//   PhysicalHealth :String,
//   FamilyRelationship:String,
//   FinancialWealth:String,
//   SocialInvestment:String,
//   RestandRestoration:String,
//   LongTermGoals:String,
// });

// export default mongoose.model("Survey", SurveySchema);



const mongoose = require("mongoose");

const SurveySchema = new mongoose.Schema(
  {
    Name:{type:String},
    key1: { type: String },
    value1: { type: String },
    key2: { type: String },
    value2: { type: String },
    key3: { type: String },
    value3: { type: String },
    key4: { type: String },
    value4: { type: String },
    key5: { type: String },
    value5: { type: String },
    key6: { type: String },
    value6: { type: String },
    key7: { type: String },
    value7: { type: String },
    key8: { type: String },
    value8: { type: String },
    key9: { type: String },
    value9: { type: String },
    key10: { type: String },
    value10: { type: String },
    key11: { type: String },
    value11: { type: String },
    key12: { type: String },
    value12: { type: String },
    key13: { type: String },
    value13: { type: String },
    key14: { type: String },
    value14: { type: String },
    key15: { type: String },
    value15: { type: String },
    key16: { type: String },
    value16: { type: String },
    key17: { type: String },
    value17: { type: String },
    key18: { type: String },
    value18: { type: String },
    key19: { type: String },
    value19: { type: String },
    key20: { type: String },
    value20: { type: String },
    key21: { type: String },
    value21: { type: String },
    key22: { type: String },
    value22: { type: String },
    key23: { type: String },
    value23: { type: String },
    key24: { type: String },
    value24: { type: String },
    key25: { type: String },
    value25: { type: String },
    key26: { type: String },
    value26: { type: String },
    key27: { type: String },
    value27: { type: String },
    key28: { type: String },
    value28: { type: String },
    key29: { type: String },
    value29: { type: String },
    key30: { type: String },
    value30: { type: String },
    key31: { type: String },
    value31: { type: String },
    key32: { type: String },
    value32: { type: String },
    key33: { type: String },
    value33: { type: String },
    key34: { type: String },
    value34: { type: String },
    key35: { type: String },
    value35: { type: String },
    key36: { type: String },
    value36: { type: String },
    key37: { type: String },
    value37: { type: String },
    key38: { type: String },
    value38: { type: String },
    key39: { type: String },
    value39: { type: String },
    key40: { type: String },
    value40: { type: String },
    key41: { type: String },
    value41: { type: String },
    key42: { type: String },
    value42: { type: String },
    key43: { type: String },
    value43: { type: String },
    key44: { type: String },
    value44: { type: String },
    key45: { type: String },
    value45: { type: String },
    key46: { type: String },
    value46: { type: String },
    key47: { type: String },
    value47: { type: String },
    key48: { type: String },
    value48: { type: String },
    key49: { type: String },
    value49: { type: String },
    key50: { type: String },
    value50: { type: String },
    key51:{type: String },
    value51: { type: String },
    key52:{type: String },
    value52: { type: String },
    key53:{type: String },
    value53: { type: String },
    key54:{type: String },
    value54: { type: String },
    key55:{type: String },
    value55: { type: String },
    key56:{type: String },
    value56: { type: String },
    key57:{type: String },
    value57: { type: String }
  }
);

const Survey = mongoose.model("Survey", SurveySchema);

module.exports = Survey;

